apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-demo-backend
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - image: docker.io/stiforr/serverless-demo-backend:latest
          ports:
            - containerPort: 1337
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 3
